# https://taskfile.dev
version: "3"
tasks:
  ## Setup
  show-node-env:
    desc: node version
    cmds:
      - |
        which node
        node --version
        asdf nodejs nodebuild --version

  install-asdf-nodejs:
    desc: install nodejs as https://github.com/asdf-vm/asdf-nodejs
    cmds:
      - asdf plugin-add nodejs || true
      - ASDF_NODEJS_VERBOSE_INSTALL=true asdf install nodejs 20.10.0
      - asdf global nodejs 20.10.0

      # NODEJS_ORG_MIRROR - official mirror https://nodejs.org/dist/ is default. If you are in China, you can set it to https://npm.taobao.org/mirrors/node/
      # NODEJS_ORG_MIRROR=https://npm.taobao.org/mirrors/node/ asdf install nodejs 20.10.0

      ## mirrors taobao
      # npm install -g cnpm --registry=https://registry.npm.taobao.org
      # alias cnpm="npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc"
      # cnpm sync connect
      # cnpm install connect
